# Paramètres de déploiement Netlify
[build]
  publish = "."
  command = ""

# Redirection de toutes les URL vers index.html pour les applications SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# En-têtes personnalisés pour améliorer la sécurité
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https:;"
